version: '3'

services:
  api-service: 
    container_name: api-service
    build:
      context: api-service
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - message-queue
  
  data-processor: 
    container_name: data-processor
    build:
      context: data-processor
      dockerfile: Dockerfile
    depends_on:
      - message-queue

  database:
    container_name: db-service
    image: mongo:5
    depends_on:
      - message-queue
  
  message-queue:
    container_name: message-service
    image: rabbitmq:3

  